version: '3'
services:
  db: # MySQLが起動するコンテナ
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    environment:
      MYSQL_USER: app_user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_HOST: db
      # MYSQL_DATABASE: sample_app_development
      TZ: Asia/Tokyo
    volumes:
      - ./db/mysql/volumes:/var/lib/mysql-files
    ports:
      - "3300:3306"

  api: # Railsが起動するコンテナ
    build: ./api
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    container_name: sample_app_rails_api_1
    volumes:
      - ./api:/myapp
      - ./api/vendor/bundle:/myapp/vendor/bundle
    environment: 
      MYSQL_USER: app_user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_HOST: db
    ports:
      - "3001:3001"
    depends_on:
      - db
    tty: true
    stdin_open: true

  front: # Reactが起動するコンテナ
    build: ./front
    volumes:
      - ./front:/myapp/front
    command: sh -c "cd front && yarn start --host 0.0.0.0 --port 3000"
    ports:
      - 3000:3000
    depends_on:
      - api
volumes:
  mysql-data: {}
